apiVersion: v1
kind: Service
metadata:
  name: backend-service-2022bcd0008
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30036
